language: node_js
sudo: false
node_js:
  - "8"
  - "7"
  - "6"
install:
  - npm install
  - npm install -g codecov
script:
  - npm run test-standard
  - npm run coverage && codecov
notifications:
  email: false
cache:
  directories:
    - $HOME/.npm
    - node_modules
